To PATH

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,7 +4,7 @@ set -e
 #set -x
 
 indent() {
-    sed -u 's/^/      /'
+    sed -u 's/^/       /'
 }
 
 export_env_dir() {
@@ -29,9 +29,13 @@ ENV_DIR="$3"
 export_env_dir $ENV_DIR
 
 # Formulate repo API URL
-REPO_OWNER="${REPO_OWNER:-heroku}"
-REPO_PROJECT="${REPO_PROJECT:-heroku-integration-service-mesh}"
-API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_PROJECT}/releases/latest"
+REPO_OWNER="${HEROKU_INTEGRATION_SERVICE_MESH_REPO_OWNER:-heroku}"
+REPO_PROJECT="${HEROKU_INTEGRATION_SERVICE_MESH_REPO_PROJECT:-heroku-integration-service-mesh}"
+if [ -z "$HEROKU_INTEGRATION_SERVICE_MESH_RELEASE_VERSION" ]; then
+    API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_PROJECT}/releases/latest"
+else
+    API_URL="https://api.github.com/repos/heroku/heroku-integration-service-mesh/releases/tags/${HEROKU_INTEGRATION_SERVICE_MESH_RELEASE_VERSION}"
+fi
 
 # Require jq util
 if ! command -v jq > /dev/null; then
@@ -41,13 +45,36 @@ if ! command -v jq > /dev/null; then
 fi
 
 # Setup release vars
-LATEST_RELEASE_JSON=$(curl -s $API_URL)
-LATEST_TAG=$(echo $LATEST_RELEASE_JSON | jq .tag_name)
-DOWNLOAD_URL=$(echo $LATEST_RELEASE_JSON | jq -r '..| .browser_download_url? // empty')
+RELEASE_JSON=$(curl -s $API_URL)
+MESSAGE=$(echo $RELEASE_JSON | jq .message)
+if [ ! -z "${MESSAGE}" ] && [ "${MESSAGE}" != "null" ]; then
+    echo " !     Unable to download Heroku Integration Service Mesh: ${MESSAGE}"
+    exit 1
+fi
+
+TAG=$(echo $RELEASE_JSON | jq .tag_name)
+DOWNLOAD_URL=$(echo $RELEASE_JSON | jq -r '..| .browser_download_url? // empty')
 BINARY_FILE="${BINARY_FILE:-$(echo $DOWNLOAD_URL | rev | cut -d '/' -f 1 | rev | cut -d '.' -f1)}"
+VENDOR_DIR="vendor/heroku-integration/bin"
+DOWNLOAD_INSTALL_DIR="$BUILD_DIR/$VENDOR_DIR"
+mkdir -p $DOWNLOAD_INSTALL_DIR
 
 # Download
-echo "------> Installing Heroku Integration Service Mesh, version $LATEST_TAG..."
-cd $BUILD_DIR && curl -JLs $DOWNLOAD_URL | tar xz
-echo "Installing... done" | indent
-echo "------> Ensure that Heroku Integration Service Mesh's install binary ($BINARY_FILE) is configured in your Procfile's web process to start your app, eg '$BINARY_FILE <app startup command>'" | indent
+echo "-----> Installing version $TAG of Heroku Integration Service Mesh..."
+echo "Downloading $BINARY_FILE..." | indent
+CURRENT_DIR=`echo $PWD`
+cd $DOWNLOAD_INSTALL_DIR && curl -JLs $DOWNLOAD_URL | tar xz
+cd $CURRENT_DIR
+
+if [ ! -f "$DOWNLOAD_INSTALL_DIR/$BINARY_FILE" ]; then
+    echo " !     Heroku Integration Service Mesh binary not found at $DOWNLOAD_INSTALL_DIR/$BINARY_FILE!"
+    exit 1
+fi
+
+echo "Installing $BINARY_FILE..." | indent
+PROFILE_PATH="$BUILD_DIR/.profile.d/$BINARY_FILE.sh"
+mkdir -p $(dirname $PROFILE_PATH)
+echo 'export PATH="$PATH:'$VENDOR_DIR'"' >> $PROFILE_PATH
+
+echo "Done!" | indent
+echo "-----> Ensure that $BINARY_FILE is configured in your Procfile's web process to start your app, eg $BINARY_FILE <app startup command>"
